import logging
import asyncio
from typing import Any
from uuid import uuid4
import json
import re
import os
import argparse

import httpx

from a2a.client import A2AClient
from a2a.types import MessageSendParams, SendMessageRequest

from utils.AtoA_architecture import agent_card  # ← IMPORTANT


def load_dataset(dataset_path, language, task):
    if  task == "task1":
        path = os.path.join(dataset_path, language, f"{task}_{language}_1.json")
        fields = ["feature_description", "content"]  # [function, code]
    elif task == "task2":
        path = os.path.join(dataset_path, language, f"{task}_{language}_final.json")
        fields = ["files", "content"]  # [files description, their content]
    else: 
        path = os.path.join(dataset_path, language, f"{task}_{language}_new.json")
        fields = ["description", "function"] # [repo description, its functions]
    with open(path, "r") as f:
        dataset = json.load(f)

    message_payloads = []

    for sample in dataset:

        # Concaténation des champs demandés
        text_parts = []
        for field in fields:
            value = sample.get(field)
            if value:
                text_parts.append(str(value))

        combined_text = "\n\n".join(text_parts).strip()

        # Construction du payload A2A
        payload = {
            "message": {
                "role": "user",
                "messageId": uuid4().hex,
                "parts": [
                    {
                        "kind": "text",
                        "text": combined_text,
                    }
                ],
            }
        }
        message_payloads.append(payload)

    return message_payloads


####################
def format_save_results(responses, dataset_path, res_dir, task, language, model_name, type_agent="AtoA"):
    # ========================
    # Load dataset (for GT)
    # ========================
    if task == "task1":
        path = os.path.join(dataset_path, language, f"{task}_{language}.json")
        gt_field = "modified_complete_code"
    elif task == "task2":
        path = os.path.join(dataset_path, language, f"{task}_{language}_final.json")
        gt_field = "gt"
    else:
        path = os.path.join(dataset_path, language, f"{task}_{language}_new.json")
        gt_field = "gt"

    with open(path, "r") as f:
        dataset = json.load(f)

    # ========================
    # Create output directory
    # ========================
    save_dir = os.path.join(
        res_dir, task, type_agent, f"{language}/{model_name}-{language}"
    )
    os.makedirs(save_dir, exist_ok=True)

    name = model_name.split("/")[-1]
    evalpath = os.path.join(save_dir, f"{name}_predictions.json")

    print(f"Results directory: {save_dir}")

    # ========================
    # Build final responses
    # ========================
    final_responses = []

    for i, (response, sample) in enumerate(zip(responses, dataset)):

        formatted = response.model_dump(mode="json", exclude_none=True)

        text = formatted["result"]["status"]["message"]["parts"][0]["text"]

        # Extract last JSON block generated by model
        try:
            last_json_start = text.rfind("{")
            pred_json = json.loads(text[last_json_start:])
        except Exception:
            pred_json = {}

        # Ground truth extraction
        gt_value = sample.get(gt_field, {})

        # If gt is not dict, wrap it
        if not isinstance(gt_value, dict):
            gt_value = {gt_field: gt_value}

        result_entry = {
            "idx": sample.get("idx", i),
            "pred": pred_json,
            "gt": gt_value,
        }

        final_responses.append(result_entry)

    # ========================
    # Save results
    # ========================
    with open(evalpath, "w") as f:
        json.dump(final_responses, f, indent=2, ensure_ascii=False)

    # return final_responses


##################@##

async def main(message_payloads, ):

    logging.basicConfig(level=logging.INFO)
    logger = logging.getLogger(__name__)
    timeout = httpx.Timeout(
        connect=10.0,
        read=120.0,
        write=10.0,
        pool=10.0,
    )

    limits = httpx.Limits(
        max_connections=100,
        max_keepalive_connections=20,
    )

    async with httpx.AsyncClient(
        timeout=timeout,
        limits=limits) as httpx_client:

        # Utiliser directement l'agent_card local
        client = A2AClient(
            httpx_client=httpx_client,
            agent_card=agent_card,
        )

        logger.info("A2AClient initialized with local agent_card.")

        # Envoie du message adapté à ton agent

        # Use non-streaming request since agent has streaming=False
        tasks = []

        for payload in message_payloads:
            message_request = SendMessageRequest(
                id=str(uuid4()),
                params=MessageSendParams(**payload),
            )
            tasks.append(client.send_message(message_request))

        responses = await asyncio.gather(*tasks)

        return responses



if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Run model evaluation via A2A")
    parser.add_argument("--model_name", type=str, required=True, help="Anthropic model name")
    parser.add_argument("--language", type=str, required=True)
    parser.add_argument("--task", type=str, default="task1")
    parser.add_argument("--dataset_path", type=str, default="./data")
    parser.add_argument("--res_dir", type=str, default="./results")
    args = parser.parse_args()

    message_payloads = load_dataset(args.dataset_path, args.language, args.task)
    responses = asyncio.run(main(message_payloads=message_payloads))
    format_save_results(responses, 
                        args.dataset_path, 
                        args.res_dir, 
                        args.task, 
                        args.language, 
                        args.model_name)